### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by afrizalfi** [incrediblesound/story-graph#22]
I wanna try to train your code with your file example.txt. I run the Syntax `node generateWorld example.txt myWorld.js` in the terminal and get this error

```/home/StoryGraph/story-graph/generator/src/tokenizer.js:94
export default tokenizer;
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/afrizal/StoryGraph/story-graph/generator/generate.js:2:19)
```
This is my library version
```
node -v
v8.11.1
```
```
npm -v
5.6.0
```

**Comment by incrediblesound** [comment]
Hi @afrizalfi , sorry I didn't see this until now, I guess I missed the email notification. I'll investigate...

**Comment by incrediblesound** [comment]
Ah, OK, I see that this issue was fixed a couple months after you encountered it, try again and let me know if it works!
