### ISSUE TITLE
Errors when running examples

### ISSUE THREAD

**Issue by flipactual** [incrediblesound/story-graph#3]
Using Node 5.x, when I run this code from the README

``` sh
node examples/forest.js
```

I get this error 

```
/Users/flip/dev/story-graph/src/world/components/time.js:12
            world.removeThing(thing.id);
                  ^

TypeError: world.removeThing is not a function
    at /Users/flip/dev/story-graph/src/world/components/time.js:12:10
    at arrayEach (/Users/flip/dev/story-graph/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/flip/dev/story-graph/node_modules/lodash/index.js:3345:13)
    at Object.advance (/Users/flip/dev/story-graph/src/world/components/time.js:10:4)
    at World.makeStory (/Users/flip/dev/story-graph/src/world/world.js:89:9)
    at Object.<anonymous> (/Users/flip/dev/story-graph/examples/forest.js:226:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

then if I run the same command again I get this error

```
/Users/flip/dev/story-graph/src/world/components/utility.js:11
    for(var i = 0; i < world.things.length; i++){
                                   ^

TypeError: Cannot read property 'length' of undefined
    at Object.removeThing (/Users/flip/dev/story-graph/src/world/components/utility.js:11:33)
    at /Users/flip/dev/story-graph/src/world/components/events.js:57:13
    at /Users/flip/dev/story-graph/node_modules/lodash/index.js:2874:23
    at /Users/flip/dev/story-graph/node_modules/lodash/index.js:3049:15
    at Function.<anonymous> (/Users/flip/dev/story-graph/node_modules/lodash/index.js:3346:13)
    at applyConsequent (/Users/flip/dev/story-graph/src/world/components/events.js:53:4)
    at Object.processEvent (/Users/flip/dev/story-graph/src/world/components/events.js:22:46)
    at World.makeStory (/Users/flip/dev/story-graph/src/world/world.js:87:22)
    at Object.<anonymous> (/Users/flip/dev/story-graph/examples/forest.js:226:19)
    at Module._compile (module.js:413:34)
```

and then they alternate back and forth from there. 

I haven't dug into it yet (happy to fix it) because I wanted to see if I was making a mistake like using an unsupported version of Node (Can we specify the `engine` field in the `package.json`?).

**Comment by incrediblesound** [comment]
Hi @flipactual ! I think this one may be something I overlooked when I converted the codebase into the current modular structure. I will take a look, but if you find the problem first feel free to make a pull request :-)

**Comment by incrediblesound** [comment]
OK @flipactual I fixed the bugs. There were some things I overlooked during refactoring.

**Comment by flipactual** [comment]
Fantastic, thank you! 

I'd love to contribute to this — if there are, now or in the future, tasks you'd like completed, please let me know 💃🏽
